#!/bin/bash
CACHE="$HOME/.xmms2.mlib.cache"

menu() {
	STYLE="$1"
	shift
	TITLE="$1"
	shift
	DATA="$1"
	shift

	LINES=$(( `wc -l <<<"$DATA"` ))
	LINES=$(( $LINES > 35 ? 35 : $LINES ))
	case "$STYLE" in
		(multi) fmenu -i -ms -p "$TITLE" -l "$LINES" "$@" <<<"$DATA";;
		(single) fmenu -i -p "$TITLE" -l "$LINES" "$@" <<<"$DATA";;
		(line) fmenu -i -p "$TITLE" "$@" <<<"$DATA";;
	esac
}

list(){
	NUM=$( { menu single "XMMS2 playlist `xmms2 playlist active`:" "`xmms2 list "$@" | grep '\['`" | sed 's|^..\[\([^/]*\).*$|\1|'; } )
	echo "zz${NUM}zz"
	if [ "$NUM" != "" ]; then
		if [ $? == 0 ]; then
			xmms2 move $NUM 1
			xmms2 jump 1
		fi
		xmms2 play
	fi
}

added() {
  echo "here"
  if (nyxmms2 status | egrep -q "^Play"); then
    true
  else
    next
  fi
}

playlst() {
	menu single "XMMS2 playlists:" "`xmms2 playlist list`" "$@" | sed 's/^[ ->]*//' | xargs -L1 xmms2 playlist load
}

media() {
	MLIB="$HOME/.config/xmms2/medialib.db"
	menu multi "XMMS2 Search:" "`cat $CACHE`" "$@" | awk -F '|' '{print $1}' | ( xargs -L1 xmms2 addid && added )
}

update() {
		xmms2 mlib search 'url:*' >$CACHE
}

last24hours() {
	TIME=`date "+%s"`
	TIME=$((TIME-24*3600))
        menu multi "XMMS2 Search:" "`xmms2 mlib search "laststarted>=$TIME"`" "$@" | awk -F '|' '{print $1}' | ( xargs -L1 xmms2 addid && added )
}

last3hours() {
	TIME=`date "+%s"`
	TIME=$((TIME-3*3600))
	menu multi "XMMS2 Search:" "`xmms2 mlib search "laststarted>=$TIME"`" "$@" | awk -F '|' '{print $1}' | ( xargs -L1 xmms2 addid && added )
}

last() {
	TIME=`date "+%s"`
	TIME=$((TIME-3*3600))
	menu multi "XMMS2 Search:" "`nyxmms2 search -o -laststarted 'url:*' | head -40`" "$@" | awk -F '|' '{print $1}' | ( xargs -L1 xmms2 addid && added )
}

favourite() {
	TIME=`date "+%s"`
	TIME=$((TIME-3*3600))
	menu multi "XMMS2 Search:" "`nyxmms2 search -o -timesplayed 'url:*' | head -40`" "$@" | awk -F '|' '{print $1}' | ( xargs -L1 xmms2 addid && added )
}

next() {
	xmms2 next
	xmms2 play
}

rewind() {
	nyxmms2 seek 0
}

clear() {
	nyxmms2 clear
}

status() {
	nyxmms2 status | sed "s/^/\"/;s/$/\"/" | xargs notify-send
}

export COLUMNS=200
RUN=`echo -e "list\\nplaylst\\nmedia\\nnext\\nlast\\nrewind\\nfavourite\\nstatus\\nupdate\\nclear" | fmenu -i -qs -p "Xmms2 menu:"`
"$RUN" "$@"
